"use client";

import { useRouter } from "next/navigation";

export default function AddGymPage() {
  const router = useRouter();
    const externalUrl = "https://keniyahost.com/add-listing/";

      function openAddEditGym() {
          window.location.href = externalUrl;
            }

              return (
                  <main
                        style={{
                                minHeight: "100vh",
                                        padding: "24px",
                                                background: "#f4f7fb",
                                                        fontFamily: "Arial, sans-serif",
                                                              }}
                                                                  >
                                                                        <div
                                                                                style={{
                                                                                          maxWidth: "900px",
                                                                                                    margin: "0 auto",
                                                                                                              background: "#fff",
                                                                                                                        borderRadius: "16px",
                                                                                                                                  boxShadow: "0 8px 24px rgba(0,0,0,0.08)",
                                                                                                                                            padding: "28px",
                                                                                                                                                    }}
                                                                                                                                                          >
                                                                                                                                                                  <h1 style={{ marginTop: 0, fontSize: "28px", color: "#111827" }}>
                                                                                                                                                                            Add/edit your gym
                                                                                                                                                                                    </h1>

                                                                                                                                                                                            <p style={{ color: "#6b7280", marginBottom: "24px" }}>
                                                                                                                                                                                                      This will open your gym listing page on Keniyahost.
                                                                                                                                                                                                              </p>

                                                                                                                                                                                                                      <div
                                                                                                                                                                                                                                style={{
                                                                                                                                                                                                                                            border: "1px solid #e5e7eb",
                                                                                                                                                                                                                                                        borderRadius: "14px",
                                                                                                                                                                                                                                                                    padding: "18px",
                                                                                                                                                                                                                                                                                background: "#f9fafb",
                                                                                                                                                                                                                                                                                            marginBottom: "24px",
                                                                                                                                                                                                                                                                                                      }}
                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                        <p style={{ margin: 0, color: "#111827", fontWeight: 700 }}>
                                                                                                                                                                                                                                                                                                                                    Destination:
                                                                                                                                                                                                                                                                                                                                              </p>
                                                                                                                                                                                                                                                                                                                                                        <p style={{ margin: "6px 0 0", color: "#6b7280" }}>
                                                                                                                                                                                                                                                                                                                                                                    {externalUrl}
                                                                                                                                                                                                                                                                                                                                                                              </p>
                                                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                                                              <div style={{ display: "flex", gap: "12px", flexWrap: "wrap" }}>
                                                                                                                                                                                                                                                                                                                                                                                                        <button
                                                                                                                                                                                                                                                                                                                                                                                                                    type="button"
                                                                                                                                                                                                                                                                                                                                                                                                                                onClick={openAddEditGym}
                                                                                                                                                                                                                                                                                                                                                                                                                                            style={primaryButtonStyle}
                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Open Add/Edit Gym
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  type="button"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              onClick={() => router.push("/")}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          style={secondaryButtonStyle}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Back to Dashboard
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const primaryButtonStyle: React.CSSProperties = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                padding: "12px 18px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  border: "none",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    borderRadius: "10px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      background: "#0f172a",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        color: "#fff",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          fontWeight: 700,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            cursor: "pointer",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const secondaryButtonStyle: React.CSSProperties = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              padding: "12px 18px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                border: "1px solid #d1d5db",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  borderRadius: "10px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    background: "#fff",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      color: "#111827",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        fontWeight: 700,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          cursor: "pointer",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          };